### ISSUE TITLE
Headless Android Emulator Questions

### ISSUE THREAD

**Issue by cah-dante-taylor** [amrsa1/Android-Emulator#4]
Hello, I have a few questions regarding running the android emulator in headless mode. When running the emulator it seems that the devices are not being found. Also could you explain how the appium server will work and VNC in headless mode? I have screenshots attached at the bottom for reference. 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/110122470/218765919-a6527c98-6c88-4ea7-8f31-4297c29db09d.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/110122470/218766224-7de21c54-1666-4186-8712-015bacba8067.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/110122470/218766354-40fe1d23-d2a1-4210-9ae0-7aad5be86bfc.png">

**Comment by cah-dante-taylor** [comment]
After designating the headless emulator command and specifying the emulator the adb was still unable to be found.
<img width="937" alt="image" src="https://user-images.githubusercontent.com/110122470/218852671-71321baf-0709-4365-bceb-0af9fad0c002.png">

**Comment by amrsa1** [comment]
Will look into it, and get back to you.

**Comment by cah-dante-taylor** [comment]
Awesome thank you so much!

**Comment by amrsa1** [comment]
Hello,

Firts the shell script file name called start_vnc.sh  not bootstrap (check the read me)

Regarding the screenshot your are showing, you cant use docker exec -it .... ./start_emu_headless.sh then append it with command you have wrote, it will not override the command in the shell script 

But you can try to run the command itself using bash command

Docker exec -it containerName bash

Then use the command for emulator 


Try using -gpu off or -gpu host, also try to add -verbose to see the error log
