### ISSUE TITLE
Facing issue while emulator launch

### ISSUE THREAD

**Issue by neehalchowdekar** [amrsa1/Android-Emulator#5]
Getting this error in appium console

debug] [ADB] Emulator 'nexus' not running
[ADB] [AVD OUTPUT] WARNING | Please update the emulator to one that supports the feature(s): Vulkan
[ADB] [AVD OUTPUT] WARNING | Failed to process .ini file /root/.android/avd/nexus.avd/quickbootChoice.ini for reading.
[ADB] [AVD OUTPUT] ERROR  | x86_64 emulation currently requires hardware acceleration!
[ADB] [AVD OUTPUT] CPU acceleration status: KVM requires a CPU that supports vmx or svm
[ADB] [AVD OUTPUT] More info on configuring VM acceleration on Linux:
[ADB] [AVD OUTPUT] https://developer.android.com/studio/run/emulator-acceleration#vm-linux
[ADB] [AVD OUTPUT] General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
[ADB] [AVD OUTPUT] INFO | Storing crashdata in: /tmp/android-unknown/emu-crash.db, detection is enabled
[ADB] [AVD OUTPUT] INFO | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.

And on running  adb devices -l
List of devices attached
emulator-5554 offline transport_id:6

It is showing offline

Can u please me resolving this issue.

Thanks and Regards
Neehal

**Comment by amrsa1** [comment]
Hi Neehal,

Could you provide your OS?
what command you have used ?
Do u have VTD enabled on your bois config ?

**Comment by neehalchowdekar** [comment]
1. OS : Debian (openjdk : 11 in dockerFile)
2. Command : **emulator -avd nexus -verbose -no-boot-anim -no-window -gpu off -no-accel -no-snapshot-load**
3. For VTD we did  **cat /proc/cpuinfo | grep vmx** didn’t get anything.

**Comment by amrsa1** [comment]
> 1. OS : Debian (openjdk : 11 in dockerFile)
> 2. Command : **emulator -avd nexus -verbose -no-boot-anim -no-window -gpu off -no-accel -no-snapshot-load**
> 3. For VTD we did  **cat /proc/cpuinfo | grep vmx** didn’t get anything.
> 
> 

What if you use -accel off

**Comment by amrsa1** [comment]
Check the new docker image, feel free to open a new ticket if issue still persists

**Comment by neehalchowdekar** [comment]
Tried with the new latest code you pushed, but the same issue

FYI
![clipboard-image](https://user-images.githubusercontent.com/64627522/220619628-a612b670-d626-49b9-9fdb-8e87383db896.png)

**Comment by amrsa1** [comment]
@neehalchowdekar 
Could you check if the VTD is enabled in your bois config ? otherwise it might be that you just need more timeout, you can verify that but running the container manually 

then run 
   "docker exec -it containerName bash"
then run the command shown above in the screenshot 
   "emulator -avd ......"
open another terminal then run again 
   "docker exec -it containerName bash" 
wait for 4 or 5 min and run
   "adb devices" 
   and check if you still see device status is offline or not

**Comment by amrsa1** [comment]
Closed due to inactivity, please feel free to open another ticket if issue still persists.
