### ISSUE TITLE
Adding Nativescript to docker and not having success connecting to avd that is created

### ISSUE THREAD

**Issue by cah-dante-taylor** [amrsa1/Android-Emulator#7]
Hello, I wanted to utilize the emulator to run tests on my nativescript application that I am working on. I am not having success with getting the emulator to start still after doing all steps required, It seems that the nexus avd is created and recognized, but will not boot up when prompted. Below I will post source code that is being used, a screenshot of the docker container configurations and the result I get when trying to run nativescript.

FROM openjdk:18-jdk-slim

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /
#=============================

Install Dependenices
#=============================
SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y curl sudo wget unzip bzip2 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libnss3 libxcursor1 libpulse-dev libxshmfence-dev xauth xvfb x11vnc fluxbox wmctrl libdbus-glib-1-2

#==============================

Android SDK ARGS
#==============================
ENV ANDROID_ARCH="x86_64"
ENV ANDROID_TARGET="google_apis_playstore"
ENV API_LEVEL="33"
ENV BUILD_TOOLS="33.0.1"
ARG ANDROID_ARCH=$ANDROID_ARCH
ARG ANDROID_TARGET=$ANDROID_TARGET
ARG ANDROID_API_LEVEL="android-$API_LEVEL"
ARG ANDROID_APIS="$ANDROID_TARGET;$ANDROID_ARCH"
ARG ANDROID_BUILD_TOOLS_VERSION=$BUILD_TOOLS
ARG ANDROID_EMULATOR_PACKAGE="system-images;${ANDROID_API_LEVEL};${ANDROID_APIS}"
ARG ANDROID_PLATFORM_VERSION="platforms;${ANDROID_API_LEVEL}"
ARG ANDROID_BUILD_TOOLS="build-tools;${ANDROID_BUILD_TOOLS_VERSION}"
ARG ANDROID_CMD_VERSION="commandlinetools-linux-8092744_latest.zip"
ARG ANDROID_SDK_PACKAGES="${ANDROID_EMULATOR_PACKAGE} 
{ANDROID_BUILD_TOOLS} platform-tools"

#==============================

Set JAVA_HOME - SDK
#==============================
ENV ANDROID_SDK_ROOT=/opt/android
ENV ANDROID_HOME=/opt/android
ENV PATH "$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/${ANDROID_BUILD_TOOLS_VERSION}"
ENV DOCKER="true"

#============================================

Install required Android CMD-line tools
#============================================
RUN wget [https://dl.google.com/android/repository/${ANDROID_CMD_VERSION}](https://dl.google.com/android/repository/%24%7BANDROID_CMD_VERSION%7D) -P /tmp &&
unzip -d $ANDROID_SDK_ROOT /tmp/$ANDROID_CMD_VERSION &&
mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/tools && cd $ANDROID_SDK_ROOT/cmdline-tools && mv NOTICE.txt source.properties bin lib tools/ &&
cd $ANDROID_SDK_ROOT/cmdline-tools/tools && ls

#============================================

Install required package using SDK manager
#============================================
RUN yes Y | sdkmanager --licenses
RUN yes Y | sdkmanager --verbose --no_https ${ANDROID_SDK_PACKAGES}

#============================================

Create required emulator
#============================================
ARG EMULATOR_NAME="nexus"
ARG EMULATOR_DEVICE="Nexus 6"
ENV EMULATOR_NAME=$EMULATOR_NAME
ENV EMULATOR_DEVICE_NAME=$EMULATOR_DEVICE
RUN echo "no" | avdmanager --verbose create avd --force --name "${EMULATOR_NAME}" --device "${EMULATOR_DEVICE}" --package "${ANDROID_EMULATOR_PACKAGE}"

#====================================

Install latest nodejs, npm & appium
#====================================
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash &&
apt-get -qqy install nodejs &&
npm install -g npm &&
npm i -g appium@next --unsafe-perm=true --allow-root &&
appium driver install uiautomator2 &&
exit 0 &&
npm cache clean &&
apt-get remove --purge -y npm && \
apt-get autoremove --purge -y &&
apt-get clean &&
rm -Rf /tmp/* && rm -Rf /var/lib/apt/lists/*

Installs nativescript
RUN npm install -g nativescript
&& tns usage-reporting disable
&& tns error-reporting disable

#===================

Alias
#===================
ENV START_EMU=./start_emu.sh
ENV START_EMU_HEADLESS=./start_emu_headless.sh
ENV START_VNC=./start_vnc.sh
ENV START_APPIUM=./start_appium.sh

#===================

Ports
#===================
ENV APPIUM_PORT=4723

#=========================

Copying Scripts to root
#=========================
COPY . /

RUN chmod a+x start_vnc.sh &&
chmod a+x start_emu.sh &&
chmod a+x start_appium.sh &&
chmod a+x start_emu_headless.sh

#=======================

framework entry point
#=======================
CMD [ "/bin/bash" ]
![image](https://user-images.githubusercontent.com/110122470/222182234-5604239d-883a-453f-a9bf-1ea517e4a318.png)
![image](https://user-images.githubusercontent.com/110122470/222182327-45dc36e8-6ae5-41f2-a551-cd27f91dcd30.png)![image](https://user-images.githubusercontent.com/110122470/222182410-b1a4fcc8-5a7d-4b79-97ee-02dc6537a98b.png)

**Comment by cah-dante-taylor** [comment]
Hello, I am using a macbook pro with virtualization enabled already. I did check to make sure it is running and still recieved the error. I have noticed when adding in the nativescript code that the emulator stopped working. But when I pull the repository and build it without any modifications the emulator does operate as intended. Could nativescript have anything to do with the emulator not operating as intended?

**Comment by amrsa1** [comment]
> Hello, I am using a macbook pro with virtualization enabled already. I did check to make sure it is running and still recieved the error. I have noticed when adding in the nativescript code that the emulator stopped working. But when I pull the repository and build it without any modifications the emulator does operate as intended. Could nativescript have anything to do with the emulator not operating as intended?

Not really sure, try to build the image locally without this library, and check if it will work or not

**Comment by cah-dante-taylor** [comment]
Hello here is the result without nativescript inside the source code. The emulator appears to run after the specified command is given.<img width="1762" alt="Screenshot 2023-03-02 at 1 29 37 PM" src="https://user-images.githubusercontent.com/110122470/222520127-6967c88d-8965-427f-a7f8-c661f1c72d70.png">

**Comment by cah-kamal-balwani** [comment]
docker pull amrka/android-emulator:nexus6_playstore-linux-latest is throwing error

**Comment by cah-dante-taylor** [comment]
Hello, in the screenshot below it is showing that the emulator is showing offline after running the specified command even without nativescript installed on the container. 

![Screenshot 2023-03-02 at 3 33 30 PM](https://user-images.githubusercontent.com/110122470/222545580-55ad7cc4-1bca-427b-b467-129d0108cd5e.png)

**Comment by cah-dante-taylor** [comment]
The emulator successfully connected and ran the nativescript testing commands. Thank you for your help it is greatly appreciated!

**Comment by cah-dante-taylor** [comment]
Hello, I am running my container on a MacOs I recently switched. After running the specified commands it still searches for the emulator and times out after 3 minutes of searching.

**Comment by cah-dante-taylor** [comment]
Turns out the emulator takes awhile to boot (around 10 minutes from the initial command being ran)![Screenshot 2023-03-03 at 12 13 59 PM](https://user-images.githubusercontent.com/110122470/222784702-3a92e596-504e-4bfc-b31d-9ac67209a22e.png) this screenshot does confirm it to be up and running from the commands that you provided.

**Comment by cah-dante-taylor** [comment]
![image](https://user-images.githubusercontent.com/110122470/222800915-4a1d1db7-d3e2-4f97-8c93-b7b96151d1a7.png)
Nativescript also has identified the emulator for unit testing. Closing this as resolved. Thank you!
